name: pyport
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.9
  - numpy==1.22.4
  - scipy==1.7.3
  - pandas=2.2.3
  - matplotlib==3.7.1
  - scikit-learn==1.6.1
  - cvxpy==1.1.10
  - numba==0.53.1
  - statsmodels==0.14.0
  - pip
  - pip:
    - fastapi==0.115.6
    - finlab
    - pandas_market_calendars==4.5.1
    - plotly==5.24.1
    - pyarrow==18.1.0
    - pydantic-settings==2.7.1
    - PyQt5==5.15.4
    - PyYAML==6.0.2
    - uvicorn==0.34.0
    - wheel==0.45.1
    - yfinance==0.2.51
                
            
