name: pyport
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.0
  - pandas=1.3.0
  - scipy=1.7.3
  - matplotlib=3.2.2
  - scikit-learn=1.3.2
  - statsmodels=0.14.0
  - PyYAML=6.0.2
  - pytz=2022.5
  - python-dateutil=2.8.2
  - plotly=5.24.1
  - fastapi
  - uvicorn=0.33.0
  - pydantic=2.10.5
  - exchange-calendars=4.2.8
  - joblib
  - numba=0.49.1
  - tenacity
  - pip
  - pip:
      - mlfinlab==0.12.3
      - portfoliolab==0.2.1
      - pandas-market-calendars==4.5.1
      - yfinance==0.2.33
      - cvxpy==1.1.10
      - ecos==2.0.14
      - scs==3.2.7.post2
      - osqp==0.6.7.post3
      - qdldl==0.1.7.post5
      - frozendict==2.4.6
      - korean-lunar-calendar==0.3.1
