data_dir: str # Path to the data folder
input_files_dir: str # Folder for input files
input_files:
  - str # Name of the input file
  # - str  # Additional file names for switching

models:
  float: # Time period in years, default 1.0
    - str # Model name, default "nested_clustering"
    # - str  # Other model names

download: bool # Whether to download data
include_etf_top_holdings: bool # Whether to include the top holdings of etf inputs
min_weight: float # Minimum weight for inclusion in final weights
max_weight: float # Maximum weight allowed for any individual hodling
portfolio_max_size: int # Maximum number of assets in the portfolio
risk_free_rate: float
allow_short: bool # Whether to allow shorting (WIP)

plot_daily_returns: bool # Whether to plot daily returns
plot_cumulative_returns: bool # Whether to plot cumulative returns
plot_clustering: bool # Where to plot hierarchical clustering dendrogram
plot_anomalies: bool # Whether to plot anomalies detected by Kalman filter
plot_reversion: bool # Whether to plot mean reversion parameters

use_z_reversion: bool # Whether to adjust weights with zscore-based mean reversion
use_ou_reversion: bool # Whether to adjust weights with OU process mean reversion
use_anomaly_filter: bool # Whether to filter assets with anomalous returns
use_decorrelation: bool # Whether to filter correlated assets

mean_reversion_strength: float # How much to weight mean reversion signals when adjusting weights

test_mode: bool # Whether to enable test mode
test_data_visible_pct: float # Percentage of test data to show

model_config:
  nested_clustering:
    sharpe: bool # Whether cluster optimization goal is sharpe or minvar
