folder: data # store price data csv
input_files: # csv containing symbols to load
  - test
musicPath: '' # completion notification sound
ignored_symbols: # enter a list of symbols to ignore
  - None
models: # time period: - model name e.g. mc, mc2, herc
  3.00:
    - mc
  1.00:
    - mc
use_cached_data: true 
min_weight: 0.00 # clip symbols with weights below this threshold in output
portfolio_max_size: 20 # limit portfolio size based on sorted weights
sort_by_weights: true # sort weights in desc order in output
plot_daily_returns: false
plot_cumulative_returns: true
verbose: false
test_mode: true
test_data_visible_pct: 1.0 # percentage of df data to view when in test mode
optimization_config: # model specific params
  hrp:
    linkage: single
  herc:
    risk_measure: conditional_drawdown_risk
    linkage: ward
  nco:
    sharpe: false
  nco2:
    sharpe: true
  mc:
    sharpe: false
    num_obs: 200
    num_sims: 32
    kde_bandwidth: 0.05
    lw_shrinkage: false
  mc2:
    sharpe: true
    num_obs: 200
    num_sims: 32
    kde_bandwidth: 0.05
    lw_shrinkage: false
  olmar:
    method: 1
    epsilon: 11
    window: 3
    alpha: 0.11
  rmr:
    epsilon: 17
    n_iteration: 60
    window: 72
    tau: 0.07
  scorn:
    rho: 0.21
    window: 21
    resample: D
  fcornk:
    rho: 5
    window: 3
    lambd: 3
    k: 5
    resample: W
  cla:
    solution: min_volatility
  cla2:
    solution: max_sharpe
  efficient_risk: 0.5
  efficient_return: 0.5
  risk_aversion: 3